import Providers from "@/app/provider"
import Header from "@/components/Header"

import { GlobalStyle } from "@chakra-ui/react"

export const metadata = {
    title: 'Loja',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <body>
                <Providers>
                    <GlobalStyle />
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    )
}
