
import Providers from "../provider"
import StyledComponentsRegistry from "../registry"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="top-center"
          theme="colored"
          autoClose={8000}
          hideProgressBar
        />
        <StyledComponentsRegistry>
          <Providers>
            {children}
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
